services:
  easy-cass-mcp:
    image: rustyrazorblade/easy-cass-mcp:latest
    container_name: easy-cass-mcp
    environment:
      - CASSANDRA_HOST=${CASSANDRA_HOST}
      - CASSANDRA_DATACENTER=${CASSANDRA_DATACENTER}
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 6<> /dev/tcp/localhost/8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
      # To install additional plugins, uncomment and add plugin names:
      - OPENSEARCH_PLUGINS_INSTALL=analysis-icu,analysis-kuromoji,analysis-smartcn,analysis-phonetic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    restart: unless-stopped
    network_mode: host

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://localhost:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    volumes:
      - opensearch_dashboards_data:/usr/share/opensearch-dashboards/data
    restart: unless-stopped
    network_mode: host
    depends_on:
      - opensearch

  data-prepper:
    image: opensearchproject/data-prepper:latest
    container_name: data-prepper
    volumes:
      - ./data-prepper-pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml:ro
    environment:
      - JAVA_OPTS=-Xms256m -Xmx256m
    restart: unless-stopped
    network_mode: host
    depends_on:
      - opensearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4900/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    environment:
      - GOMEMLIMIT=256MiB
    restart: unless-stopped
    network_mode: host
    depends_on:
      - opensearch
      - data-prepper

volumes:
  opensearch_data:
  opensearch_dashboards_data: