#!/bin/bash

CASS_PID=$(cat /var/run/cassandra/cassandra.pid )
OUTPUT=$(mktemp -u -p /tmp 'cassandra-profile-XXXX.svg')

(
cd "$(dirname "$0")"

sudo ./profiler.sh $@ -f $OUTPUT $CASS_PID
)

cp $OUTPUT .

basename $OUTPUT
