package com.rustyrazorblade.easydblab

import com.fasterxml.jackson.databind.ObjectMapper
import com.rustyrazorblade.easydblab.core.YamlDelegate
import io.github.oshai.kotlinlogging.KotlinLogging
import org.koin.core.component.KoinComponent
import java.io.File

data class Context(
    val easyDbLabUserDirectory: File,
    val isMcp: Boolean = false,
    /**
     * Working directory for lab operations (cluster state, logs, etc.).
     * Defaults to the JVM's current working directory.
     * Can be overridden in tests to use a temp directory.
     */
    val workingDirectory: File = File(System.getProperty("user.dir")),
) : KoinComponent {
    companion object {
        /**
         * Create a Context for regular CLI execution
         */
        fun forCli(easyDbLabUserDirectory: File): Context = Context(easyDbLabUserDirectory, isMcp = false)

        /**
         * Create a Context for MCP server execution
         */
        fun forMcp(easyDbLabUserDirectory: File): Context = Context(easyDbLabUserDirectory, isMcp = true)
    }

    val log = KotlinLogging.logger {}

    /**
     * Profile setup.  User can override the default profile using a env var.
     * Long term, should probably make this something they can do via a command.
     * Will be useful once multiple cloud providers are supported.
     */
    var profile = System.getenv("EASY_DB_LAB_PROFILE") ?: "default"
    var profilesDir = File(easyDbLabUserDirectory, "profiles")
    var profileDir = File(profilesDir, profile)

    init {
        profileDir.mkdirs()
    }

    val home = File(System.getProperty("user.home"))

    /**
     * Version is either supplied by the in-repo script,
     * or the version generated by the application plugin
     */
    val version = System.getProperty("easydblab.version")?.toInt() ?: 0
    val appHome = System.getProperty("easydblab.apphome")
    val packerHome = "$appHome/packer/"
    val cassandraVersionsExtra = File(profileDir, "cassandra_versions")

    /**
     * Please use this for reading and writing yaml to objects
     *
     * Example usage:
     *
     * val state = mapper.readValue<MyStateObject>(json)
     */
    val yaml: ObjectMapper by YamlDelegate()
}
