#!/bin/bash

YAML="${CASSANDRA_YAML:-/etc/cassandra.yaml}"
SEARCH=$1


rg -N -v '^\s*#[^:]*$' $CASSANDRA_YAML | \
rg -N -A5 -B5 -i --context-separator="====================================" -e "$SEARCH" | \
awk NF
