#!/bin/bash


CPID=$(cassandra-pid)

if [[ $CPID -eq 0 ]]; then
  echo "CASSANDRA NOT RUNNING: FAIL"
  exit 1
fi

echo "Waiting for JMX"
while ! ss -tulwn | grep ':7199' ; do sleep 1; done

while true; do

# first check if it's up

  CPID=$(cassandra-pid)

  if [[ $CPID -eq 0 ]]; then
    echo "CASSANDRA HAS SHUT DOWN: FAIL"
    exit 1
  fi

  sjk-mx -b org.apache.cassandra.db:type=StorageService -mg -f OperationMode | grep NORMAL
  status=$?

  if [[ $status -eq 0 ]]; then
    echo "OK"
    exit 0
  fi

  sleep 1

done


